/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtletaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Atleta;
import model.CampoVazioException;
import model.NumeroNegativoException;

/**
 *
 * @author aluno
 */
public class FrmAtleta extends javax.swing.JFrame {
    private AtletaController atletaController;
    private  DefaultTableModel  dados;
    
    /**
     * Creates new form FrmAtleta
     */
    public FrmAtleta() {
        dados = new DefaultTableModel();
        dados.setRowCount(0);
        dados.addColumn("Código");
        dados.addColumn("Nome");
        dados.addColumn("Idade");
        dados.addColumn("Peso");
        dados.addColumn("Altura");
        atletaController = new AtletaController();
        initComponents();
        tblAtletas.setModel(dados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        btnMediaPesos = new javax.swing.JButton();
        btnAlunoMaisAlto = new javax.swing.JButton();
        btnInfoIdades = new javax.swing.JButton();
        btnAtletas = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        btnBuscaCodigo = new javax.swing.JButton();
        btnBuscaNome = new javax.swing.JButton();
        btnBuscaPeso = new javax.swing.JButton();
        btnBuscaAltura = new javax.swing.JButton();
        btnBuscaIdade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtExcluir = new javax.swing.JTextField();
        lblCodigo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtletas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblCodigo.setText("Código");

        lblPeso.setText("Peso");

        lblAltura.setText("Altura");

        lblIdade.setText("Idade");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnMediaPesos.setText("Média Pesos");
        btnMediaPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaPesosActionPerformed(evt);
            }
        });

        btnAlunoMaisAlto.setText("Aluno mais alto");
        btnAlunoMaisAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoMaisAltoActionPerformed(evt);
            }
        });

        btnInfoIdades.setText("Informações sobre idades");
        btnInfoIdades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoIdadesActionPerformed(evt);
            }
        });

        btnAtletas.setText("Atletas");
        btnAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtletasActionPerformed(evt);
            }
        });

        lblCodigo1.setText("Código");

        btnBuscaCodigo.setText("Busca por código");
        btnBuscaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCodigoActionPerformed(evt);
            }
        });

        btnBuscaNome.setText("Busca por Nome");
        btnBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNomeActionPerformed(evt);
            }
        });

        btnBuscaPeso.setText("Busca por Peso");
        btnBuscaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPesoActionPerformed(evt);
            }
        });

        btnBuscaAltura.setText("Busca por Altura");
        btnBuscaAltura.setToolTipText("");
        btnBuscaAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaAlturaActionPerformed(evt);
            }
        });

        btnBuscaIdade.setText("Busca por Idade");
        btnBuscaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaIdadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Busca");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblCodigo2.setText("Código");

        tblAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAtletas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIdade)
                                            .addComponent(lblAltura))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblCodigo2)
                                .addGap(10, 10, 10)
                                .addComponent(txtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodigo1)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnBuscaPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscaNome)
                                        .addGap(0, 0, 0)
                                        .addComponent(btnBuscaAltura))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(141, 141, 141))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(btnBuscaIdade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscaCodigo)))
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMediaPesos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlunoMaisAlto)
                                .addGap(5, 5, 5)
                                .addComponent(btnInfoIdades)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtletas)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo1)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscaNome)
                            .addComponent(btnBuscaPeso)
                            .addComponent(btnBuscaAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscaIdade)
                            .addComponent(btnBuscaCodigo))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo2)
                            .addComponent(txtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeso)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdade)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnMediaPesos)
                    .addComponent(btnAlunoMaisAlto)
                    .addComponent(btnAtletas)
                    .addComponent(btnInfoIdades))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        try {
            String codigo = txtCodigo.getText();
            String nome = txtNome.getText();
            if(codigo.equals("") || nome.equals("") || txtAltura.getText().equals("") || txtIdade.getText().equals("") || txtPeso.getText().equals("")){
                throw new CampoVazioException();            
            }
            
            float altura = Float.parseFloat(txtAltura.getText());
            float peso = Float.parseFloat(txtPeso.getText());
            int idade = Integer.parseInt(txtIdade.getText());
            
            if(altura < 0 || peso < 0 || idade < 0) {
                throw new NumeroNegativoException();
            }            
            
            String response = atletaController.cadastrarAtleta(codigo, nome, altura, idade, peso);
            mostrarAtletas();
            JOptionPane.showMessageDialog(null, response);
        } catch(CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch(NumeroNegativoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException e) {         
            JOptionPane.showMessageDialog(null, "Altura, peso e idade devem ser números");
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnMediaPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaPesosActionPerformed
        float mediaPesos = atletaController.calcularMediaPeso();
        
        JOptionPane.showMessageDialog(null, Float.toString(mediaPesos));
    }//GEN-LAST:event_btnMediaPesosActionPerformed

    private void btnAlunoMaisAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoMaisAltoActionPerformed
        String atletaMaisAltoNome = atletaController.getAlunoMaisAlto();
        JOptionPane.showMessageDialog(null, atletaMaisAltoNome);
    }//GEN-LAST:event_btnAlunoMaisAltoActionPerformed

    private void btnInfoIdadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoIdadesActionPerformed
        String infoIdades = atletaController.getInfoIdades();
        JOptionPane.showMessageDialog(null, infoIdades);
    }//GEN-LAST:event_btnInfoIdadesActionPerformed

    private void btnAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtletasActionPerformed
        String result = new String();
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        for(Atleta a : atletas){
            result = result.concat(a.getNome() + "\n");
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnAtletasActionPerformed

    private void btnBuscaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCodigoActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        String codigo = txtBusca.getText();
        String result = "";
        
        for(Atleta a: atletas){
            if(a.getCodigo().equals(codigo)) {
                result = result.concat("Nome: " + a.getNome() + "\nCódigo: " + a.getCodigo() + "\nAltura: " + a.getAltura() + "\nIdade: " + a.getIdade() + "\nPeso: " + a.getPeso());
                break;
            }   
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnBuscaCodigoActionPerformed

    private void btnBuscaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaIdadeActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        int idade = Integer.parseInt(txtBusca.getText());
        String result = "";
        
        for(Atleta a: atletas){
            if(a.getIdade() == idade) {
                result = result.concat("Nome: " + a.getNome() + "\n");
            }   
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnBuscaIdadeActionPerformed

    private void btnBuscaAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaAlturaActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        int altura = Integer.parseInt(txtBusca.getText());
        String result = "";
        
        for(Atleta a: atletas){
            if(a.getAltura() == altura) {
                result = result.concat("Nome: " + a.getNome() + "\n");
            }   
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnBuscaAlturaActionPerformed

    private void btnBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNomeActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        String nome = txtBusca.getText();
        String result = "";
        
        for(Atleta a: atletas){
            if(a.getNome().equals(nome)) {
                result = result.concat(a.getCodigo() + " - " + a.getNome() + "\n");
            }   
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnBuscaNomeActionPerformed

    private void btnBuscaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPesoActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        int peso = Integer.parseInt(txtBusca.getText());
        String result = "";
        
        for(Atleta a: atletas){
            if(a.getPeso() == peso) {
                result = result.concat("Nome: " + a.getNome() + "\n");
            }   
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_btnBuscaPesoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        String codigo = txtExcluir.getText();
        Boolean alunoEncontrado = false;
        
        for(int i = 0; i < atletas.size(); i++) {
           if(atletas.get(i).getCodigo().equals(codigo)) {
                atletas.remove(i);
                dados.removeRow(i);
                tblAtletas.setModel(dados);
                alunoEncontrado = true;
                break;
            }    
        }
        
        if (alunoEncontrado == true){
            JOptionPane.showMessageDialog(null, "Aluno excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAtleta().setVisible(true);
            }
        });
    }
    
    public void mostrarAtletas(){
        dados.setNumRows(0);
        ArrayList<Atleta> atletas = atletaController.getAtletas();
        for(Atleta a: atletas){
            dados.addRow(new Object[]{a.getCodigo(), a.getNome(), a.getAltura(), a.getIdade(), a.getPeso()});
        }
        tblAtletas.setModel(dados);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunoMaisAlto;
    private javax.swing.JButton btnAtletas;
    private javax.swing.JButton btnBuscaAltura;
    private javax.swing.JButton btnBuscaCodigo;
    private javax.swing.JButton btnBuscaIdade;
    private javax.swing.JButton btnBuscaNome;
    private javax.swing.JButton btnBuscaPeso;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInfoIdades;
    private javax.swing.JButton btnMediaPesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTable tblAtletas;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExcluir;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
