/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import static view.FrmLanding.jogoController;

/**
 *
 * @author aluno
 */
public class FrmJogoInfos extends javax.swing.JFrame {
    private static FrmJogoInfos jogosInfoForm = null;
    DecimalFormat df = new DecimalFormat("#.##");

    /**
     * Creates new form FrmClienteInfos
     */
    private FrmJogoInfos() {
        initComponents();
    }
    
    public static FrmJogoInfos getInstancia(){
        if(jogosInfoForm == null){
            jogosInfoForm = new FrmJogoInfos();
        }
        return jogosInfoForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMaisCaro = new javax.swing.JButton();
        btnMaisBarato = new javax.swing.JButton();
        btnMediaPreco = new javax.swing.JButton();
        btnMaisCarosMedia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnMaisCaro.setText("Jogo mais caro");
        btnMaisCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisCaroActionPerformed(evt);
            }
        });

        btnMaisBarato.setText("Jogo mais barato");
        btnMaisBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisBaratoActionPerformed(evt);
            }
        });

        btnMediaPreco.setText("Média de preços");
        btnMediaPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaPrecoActionPerformed(evt);
            }
        });

        btnMaisCarosMedia.setText("Jogos mais caros que a média");
        btnMaisCarosMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisCarosMediaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Informações sobre Jogos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMaisCarosMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMaisBarato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMediaPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMaisCaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnMaisCaro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaisBarato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMediaPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaisCarosMedia)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaisCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisCaroActionPerformed
        JOptionPane.showMessageDialog(null, "Jogo cadastrado mais caro: \n" + jogoController.jogoMaisCaro());
    }//GEN-LAST:event_btnMaisCaroActionPerformed

    private void btnMaisBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisBaratoActionPerformed
        JOptionPane.showMessageDialog(null, "Jogo cadastrado mais barato: \n" + jogoController.jogoMaisBarato());
    }//GEN-LAST:event_btnMaisBaratoActionPerformed

    private void btnMediaPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaPrecoActionPerformed
        JOptionPane.showMessageDialog(null, "Media de preço da loja: \n R$" + df.format(jogoController.jogoMediaPrecos()));
    }//GEN-LAST:event_btnMediaPrecoActionPerformed

    private void btnMaisCarosMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisCarosMediaActionPerformed
        JOptionPane.showMessageDialog(null, "Jogos com preço acima da média: \n" + jogoController.jogoQuantidadeAcimaMediaPreco());
    }//GEN-LAST:event_btnMaisCarosMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJogoInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJogoInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJogoInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJogoInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJogoInfos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaisBarato;
    private javax.swing.JButton btnMaisCaro;
    private javax.swing.JButton btnMaisCarosMedia;
    private javax.swing.JButton btnMediaPreco;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
